using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class VillageUIManager : MonoBehaviour
{
    /* Т UI */
    public GameObject menuUI;
    /* 퀢쮱칙 UI */
    public GameObject weaponUI;
    public GameObject armorUI;
    public GameObject accUI;

    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            menuUI.SetActive(true);

            Cursor.visible = true;
        }
    }
    /* UI칙 얳쐑 */
    public void CloseMenuUI()
    {
        menuUI.SetActive(false);

        Cursor.visible = false;
    }
    #region
    /* 퀢쮱칙 얳쐑 */
    // 졺쐑 UI 칙
    public void OpenWeaponUI()
    {
        weaponUI.SetActive(true);
    }

    public void CloseWeaponUI()
    {
        weaponUI.SetActive(false);
    }
    // 좭쮩쏮 UI 칙
    public void OpenArmorUI()
    {
        armorUI.SetActive(true);
    }

    public void CloseArmorUI()
    {
        armorUI.SetActive(false);
    }
    // 쮆쨮쨠쟕 UI 칙
    public void OpenAccUI()
    {
        accUI.SetActive(true);
    }

    public void CloseAccUI()
    {
        accUI.SetActive(false);
    }
    #endregion
}
